### ISSUE TITLE
Bug: 3.0.0 requires uninstall and reinstall

### ISSUE THREAD

**Issue by alandtse** [spdx/spdx-license-diff#26]
The latest release added exceptions support but didn't force a redownload of the license list which can cause an error.  Please uninstall and reinstall to force a new list to be downloaded.

**Comment by alandtse** [comment]
Correction, the workaround is going to the [Extensions page](chrome://extensions/), clicking on Inspect views `background page`, and refreshing that new window. Windows should be F5, osx: command + r

**Comment by alandtse** [comment]
Error when attempting to scan before downloading a new list.
```
Error in event handler: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at P (chrome-extension://kfoadicmilbgnicoldjmccpaicejacdh/scripts/background.js:1:34956)
    at chrome-extension://kfoadicmilbgnicoldjmccpaicejacdh/scripts/background.js:1:3748
```
